[project]
name = "library-management-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rishav", email = "rishavromyraj0706@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
library-management-project = "library_management_project:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
